### ISSUE TITLE
Error send webhook notification

### ISSUE THREAD

**Issue by Welington98** [ericferon/glpi-webhook#44]
When I try to open a ticket with the webhook activated to send the request via webhook, the screen goes white. Returning the information from the photo below with debugging enabled

![image](https://github.com/ericferon/glpi-webhook/assets/36057551/33e0754f-719d-474b-9860-dda387926be9)

**Comment by ericferon** [comment]
Hi,
Which authentication type has been chosen in the webhook definition ?
(You must choose one among the 3 proposals).
K.r,

**Comment by isaacvicente** [comment]
I have a similar situation. I'm using Authentication Type 3 - Encoded Basic Authentication, and the REST Verb is POST.
In my config, I have a webhook address (which points to a private Mattermost instance), the secret (which is the Access Token created by the user specified bellow).

I was receiving notifications untill last week (5th Mar 2024). Since then, I don't receive any notifications whatsoever.
I've tried to create another Access Token but this didn't work.

Maybe I could change the Authentication Type? I don't know.

I'm available to any suggestions,
Cheers.

**Comment by IgorReyms** [comment]
> [isaacvicente](/isaacvicente)

Hi
Do you solve this problem?

**Comment by ericferon** [comment]
Hi,
The webhook uses the GLPI notification mechanism, but it sends an HTTP request instead of an email or a browser notification.
The plugin did not change since November 2023 ; it unlikely behaves differently from March 2024 on.
So, can you check first that there are still a notification event : please, configure a browser notification, f.i, for the same GLPI operation. If you don't receive a notification, the problem is probably in a change to the notification mechanism.
Otherwise, I will need more information to repeat the problem in my own system.
K.r,
