### ISSUE TITLE
Webhooks do not send messages after updating to the channel configured in mattermost

### ISSUE THREAD

**Issue by felixalexsandro** [ericferon/glpi-webhook#54]
Recently the Webhooks were updated and after that the messages of new tickets in GLPI do not synchronize in the mattermost channel. This integration worked perfectly before the update!

**Comment by ericferon** [comment]
Hi,
The Webhook plugin has not been updated since November 2023.
The root cause is probably elsewhere... unless you just upgraded Webhook recently !
Anyway, if the problem is due to Webhook, I need more information : error messages from php_errors.log, f.i.
Otherwise, you can activate the debug flag in your webhook definition and have a look to the webhook.log in directory files/_log ; then, try manually (with Postman, f.i) the sequence of HTTP requests to mattermost and see whether there are errors outside Webhook.
K.r,

**Comment by felixalexsandro** [comment]
Thanks!

The problem was resolved when we redid the authentication configuration with the mattermost channel.
